# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Test Flutter App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  FLUTTER_VERSION: "3.7.8"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze Flutter
        run: flutter analyze --no-pub
      - name: Run Flutter Tests
        run: flutter test --no-pub
